-- SKILLS: 64 rows
INSERT INTO SKILLS VALUES ('bash','Power Strike','swordman',1,2,500,64,'enemy','damage','atk',1,0,1,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('magnum','Flame Burst','swordman',3,4,1000,96,'area','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('endure','Iron Will','swordman',5,2,15000,0,'self','buff','atk',1,0,0,'endure','VERIFIED');
INSERT INTO SKILLS VALUES ('firstaid','First Aid','novice',1,3,6000,0,'self','heal','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('firebolt','Ember Bolt','mage',1,4,100,240,'enemy','damage','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('coldbolt','Frost Area','mage',3,5,850,150,'area','damage','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('thunderstorm','Stormbreak','mage',5,7,550,120,'area','damage','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('doublestrafe','Twin Shot','archer',1,0.7,500,300,'enemy','damage','atk',1,0,1,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('arrowshower','Arrow Rain','archer',3,4,5000,280,'area','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('piercingshot','Piercing Shot','archer',5,10,5000,320,'enemy','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('heal','Heal','acolyte',1,3,1000,160,'ally','heal','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('holylight','Radiant Light','acolyte',3,4,1500,150,'area','damage','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('holyguard','Holy Guard','acolyte',5,3,15000,0,'self','buff','matk',1,0,0,'holyguard','VERIFIED');
INSERT INTO SKILLS VALUES ('blessing','Divine Boon','acolyte',7,5,15000,150,'ally','buff','matk',1,0,0,'blessing','VERIFIED');
INSERT INTO SKILLS VALUES ('remedylight','Remedy Light','acolyte',9,20,15000,170,'self','buff','matk',1,0,0,'remedy','VERIFIED');
INSERT INTO SKILLS VALUES ('mammonite','Gold Strike','merchant',1,2,3500,72,'enemy','damage','atk',1,0,1,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('cartstrike','Cart Strike','merchant',3,3.5,3000,100,'area','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('hammerfall','Quake Hammer','merchant',5,4,4500,150,'area','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('overthrust','Power Surge','merchant',7,15,30000,0,'self','buff','atk',1,0,0,'overthrust','VERIFIED');
INSERT INTO SKILLS VALUES ('twinfang','Twin Fang','thief',1,4,2500,72,'enemy','damage','atk',1,0,1,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('venomknife','Toxin Blink','thief',3,1,7000,220,'enemy','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('shadowburst','Shadow Burst','thief',5,10,7500,110,'area','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('challenging','Challenging','swordman',7,3,5000,170,'area','debuff','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('tierra','Tierra Sharp Spear','mage',7,4,100,240,'enemy','damage','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('spiritinstinct','Spirit Instinct','archer',7,8,20000,0,'self','buff','atk',1,0,0,'spirit','VERIFIED');
INSERT INTO SKILLS VALUES ('leapshot','Leap Shot','archer',9,15,7000,170,'enemy','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('vanish','Vanish','thief',7,20,15000,0,'self','buff','atk',1,0,0,'vanish','VERIFIED');
INSERT INTO SKILLS VALUES ('viperfang','Viper Fang','mamushi',1,4,2500,200,'enemy','damage','atk',1,0,1,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('dokugiri','Dokugiri','mamushi',3,8,6000,110,'area','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('venomrupture','Venom Rupture','mamushi',5,12,8000,200,'enemy','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('dokunuri','Dokunuri','mamushi',7,15,30000,0,'self','buff','atk',1,0,0,'dokunuri','VERIFIED');
INSERT INTO SKILLS VALUES ('iaigiri','Iaigiri','kensei',1,4,2500,72,'enemy','damage','atk',1,0,1,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('oboro','Oboro Ranbu','kensei',3,12,15000,220,'enemy','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('issen','Issen','kensei',5,10,6000,220,'enemy','damage','atk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('meikyo','Meikyo Shisui','kensei',7,15,30000,0,'self','buff','atk',1,0,0,'meikyo','VERIFIED');
INSERT INTO SKILLS VALUES ('nekoflask','Fizz Flask','nekobaku',1,3,500,200,'enemy','damage','matk',1,0,1,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('tarflask','Tar Flask','nekobaku',3,5,3000,80,'area','damage','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('bigkaboom','Big Kaboom','nekobaku',5,9,5000,100,'area','damage','matk',1,0,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('catbrew','Catalyst Brew','nekobaku',7,15,30000,0,'self','buff','matk',1,0,0,'catbrew','VERIFIED');
INSERT INTO SKILLS VALUES ('swordmastery','Blade Mastery','swordman',2,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('hprecovery','Vigor','swordman',4,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('sp_recovery','Meditation','mage',2,0,0,0,'self','passive','matk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('owleye','Keen Eye','archer',2,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('vultureeye','Far Sight','archer',4,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('divineprotection','Sacred Ward','acolyte',2,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('demonbane','Fiend Slayer','acolyte',4,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('discount','Haggler','merchant',2,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('overcharge','Markup','merchant',4,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('doubleattack','Twin Strike','thief',2,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('improvedodge','Fleet Foot','thief',4,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('ironbody','Iron Body','swordman',9,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('mentality','Mentality','mage',9,0,0,0,'self','passive','matk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('magemastery','Mage Mastery','mage',11,0,0,0,'self','passive','matk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('weighttraining','Weight Training','merchant',9,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('venommastery','Venom Mastery','mamushi',2,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('numbingtoxin','Numbing Toxin','mamushi',4,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('predator','Predator''s Patience','mamushi',9,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('katanamastery','Katana Mastery','kensei',2,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('shukuchi','Shukuchi','kensei',4,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('zanshin','Zanshin','kensei',9,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('fatalsense','Fatal Sense','thief',9,0,0,0,'self','passive','atk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('alchemymastery','Alchemy Mastery','nekobaku',2,0,0,0,'self','passive','matk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('ninelives','Nine Lives','nekobaku',4,0,0,0,'self','passive','matk',1,1,0,NULL,'VERIFIED');
INSERT INTO SKILLS VALUES ('catreflex','Feline Reflex','nekobaku',9,0,0,0,'self','passive','matk',1,1,0,NULL,'VERIFIED');
