// Starter Pack (Ae)
{id:"starter",key:"mall-starter-1",name:"Starter Pack",gold:160,pieces:[{slot:"head",name:"Lumina Circlet",bonuses:{def:6,mdef:4,vit:3}},{slot:"face",name:"Lumina Monocle",bonuses:{mdef:5,dex:3,hit:4}},{slot:"mouth",name:"Lumina Scarf",bonuses:{mdef:5,hp:150}},{slot:"armor",name:"Lumina Coat",bonuses:{def:9,hp:300,vit:3}},{slot:"shield",name:"Lumina Guard",bonuses:{def:6,mdef:3}},{slot:"garment",name:"Lumina Cape",bonuses:{def:5,flee:8,agi:3}},{slot:"shoes",name:"Lumina Boots",bonuses:{def:5,flee:6,hp:150}},{slot:"accessory1",name:"Lumina Ring",bonuses:{crit:6,hit:6,luk:3}},{slot:"accessory2",name:"Lumina Earring",bonuses:{matk:8,sp:60,int:3}},{slot:"sword",template:"sword",name:"Lumina Sword",bonuses:{atk:16,hit:8,str:4}},{slot:"sword",template:"knife",name:"Lumina Knife",bonuses:{atk:13,hit:8,agi:4}},{slot:"sword",template:"kunai",name:"Lumina Kunai",bonuses:{atk:15,hit:8,dex:4}},{slot:"sword",template:"katana",name:"Lumina Katana",bonuses:{atk:15,hit:8,agi:4}},{slot:"sword",template:"hammer",name:"Lumina Hammer",bonuses:{atk:17,hit:6,str:4}},{slot:"sword",template:"bow",name:"Lumina Bow",bonuses:{atk:15,hit:8,dex:4}},{slot:"sword",template:"rod",name:"Lumina Rod",bonuses:{matk:16,int:5}},{slot:"sword",template:"flask",name:"Lumina Flask",bonuses:{matk:15,int:3,agi:3}},{slot:"sword",template:"quarterstaff",name:"Lumina Staff",bonuses:{atk:10,matk:8,int:3}}]}

].name} x${A.count}`],[Ah,`${Yt(A.gold)} Gold`],[Mf,`${Yt(u-A.gold)} Gold`]],"","",Af,()=>Lo({type:"mallBuy",offer:A.id}))}),S.querySelectorAll("[data-gold-pack]").forEach(w=>w.onclick=()=>{const A=zf.find(y=>y.id===w.dataset.goldPack);if((se?.gold??0)<A.gold){_t("Gold ไม่พอ — ซื้อ Gold หรือแลกด้วย Silver ที่ตลาด Gold",!0);return}const u=se?.gold??0;ko(KF,[[e1,`Premium ${A.days} วัน`],[Ah,`${Yt(A.gold)} 

emium ${A.days} วัน`],[Ah,`${Yt(A.gold)} Gold`],[Mf,`${Yt(u-A.gold)} Gold`]],"","",Af,()=>Lo({type:"premiumBuy",pack:A.id}))}),S.querySelectorAll("[data-mall-page]").forEach(w=>w.onclick=()=>Pf(Number(w.dataset.mallPage))),S.querySelectorAll("[data-mall-step]").forEach(w=>w.onclick=()=>{Pf(Sr+Number(w.dataset.mallStep)),S.querySelector(".pw-body")?.scrollTo({top:0})}),Pf(0),Bt("mall-topup").onclick=()=>{Vi=

erySelectorAll("[data-mall-page]").forEach(S=>S.setAttribute("aria-pressed",String(Number(S.dataset.mallPage)===Sr))),c.querySelectorAll("[data-mall-page-body]").forEach(S=>S.hidden=Number(S.dataset.mallPageBody)!==Sr),c.querySelectorAll("[data-mall-step]").forEach(S=>{const T=Sr+Number(S.dataset.mallStep);S.disabled=T<0||T>=il.length}),Bt("mall-page-no").textContent=`${Sr+1} / ${il.length}`}function wD(h

.querySelectorAll("[data-gold-pack]").forEach(w=>w.onclick=()=>{const A=zf.find(y=>y.id===w.dataset.goldPack);if((se?.gold??0)<A.gold){_t("Gold ไม่พอ — ซื้อ Gold หรือแลกด้วย Silver ที่ตลาด Gold",!0);return}const u=se?.gold??0;ko(KF,[[e1,`Premium ${A.days} วัน`],[Ah,`${Yt(A.gold)} Gold`],[Mf,`${Yt(u-A.gold)} Gold`]],"","",Af,()=>Lo({type:"premiumBuy",pack:A.id}))}),S.querySelectorAll("[data-mall-page]").fo

