;if(x){this.log(x);return}J?J.send({type:"changeClass",classId:E}):V5(this,E)&&(sB(this),this.endureUntil=0,Y5(this),this.hp=Math.min(this.maxHp,this.hp),this.sp=Math.min(Zt(this).maxSp,this.sp),this.questTick("changeClass"),this.ui(),this.log(`เปลี่ยนอาชีพเป็น ${$t[E]} แล้ว`))},E=>{if(this.deadUntil)return;if(J){J.send({type:"unlockClass",classId:E});return}const x=H5(this,E);this.log(x||`ปลดล็อกอาชีพ ${$t[E]} แล้ว — เปลี่ยนอาชีพได้ที่หน้าต่าง Class`),x||this.ui()}),XN(this,(E,x)=>this.deadUntil||!St("world-window").hidden||this.areaInfo.portals.some(C=>Math.abs(E-C.x)<50&&Math.abs(x-C.y)<60)?null:(this.groundItems.get(this.area)??[]).some(C=>Math.hypot(C.x-E,C.y-x)<24)?"loot":this.mobs.some(C=>C.ali

this.area)??[];M.push(C),this.groundItems.set(this.area,M),this.lootViews.set(C,lr(this,C)),Oh(C,this.player)}else if(E.type==="destroy")hM(this,E);else if(E.type==="equip")J5(this,E.id,E.slot)&&this.questTick("equip");else if(E.type==="unequip")Q5(this,E.slot);else if(E.type==="loadoutSave")uM(this,E.id,E.name);else if(E.type==="loadoutApply")dM(this,E.id)&&this.questTick("equip");else if(E.type==="loadoutDelete")cM(this,E.id);else if(E.type==="stat"){this.addStat(E.stat);return}this.hp=Math.min(this.hp,this.maxHp),this.ui()}};HP(),xL((E,x)=>this.useItem(E,x),E=>c({type:"drop",item:E}),(E,x)=>c({type:"lock",item:E,locked:x}),(E,x)=>c({type:"destroy",item:E,quantity:x})),l6(c),eL(E=>{J?J.send(E):this.

equip")J5(this,E.id,E.slot)&&this.questTick("equip");else if(E.type==="unequip")Q5(this,E.slot);else if(E.type==="loadoutSave")uM(this,E.id,E.name);else if(E.type==="loadoutApply")dM(this,E.id)&&this.questTick("equip");else if(E.type==="loadoutDelete")cM(this,E.id);else if(E.type==="stat"){this.addStat(E.stat);return}this.hp=Math.min(this.hp,this.maxHp),this.ui()}};HP(),xL((E,x)=>this.useItem(E,x),E=>c({type:"drop",item:E}),(E,x)=>c({type:"lock",item:E,locked:x}),(E,x)=>c({type:"destroy",item:E,quantity:x})),l6(c),eL(E=>{J?J.send(E):this.log("เปลี่ยนชื่อได้เฉพาะตอนเล่นออนไลน์")},()=>this.name??""),ZP(E=>{if(J){J.send(E);return}jP(this,E.slot,E.id??null)&&this.ui()}),o7(E=>{if(this.deadUntil)return;if(

s.deadUntil)return;if(J){J.send(E);return}const x={...this,x:this.player.x,y:this.player.y};if(E.type==="buy"){const M=fM(x,E.entry,E.quantity??1);this.silver=x.silver??0,Mx(M||"ซื้อสำเร็จ"),M||(this.questTick("buy"),lt.play("pickup"),this.ui());return}const C=pM(x,E);this.silver=x.silver,this.npcSales=x.npcSales,Cx(C),C&&this.questTick("sell"),C&&(this.log(`ขายสินค้า +${C} Silver`),this.ui())}),c6(E=>{if(this.deadUntil)return;if(e2(this,Date.now())||this.setAuto(!1),J){J.send(E);return}const x={...this,x:this.player.x,y:this.player.y},C=eM(x,E);C.ok&&(this.storage=x.storage,this.gear=x.gear,lt.play("pickup"),this.ui()),oy(C.text)},()=>J?.send({type:"storageOpen"})),HO(E=>{if(!this.deadUntil){if(J){J.

ry,E.quantity??1);this.silver=x.silver??0,Mx(M||"ซื้อสำเร็จ"),M||(this.questTick("buy"),lt.play("pickup"),this.ui());return}const C=pM(x,E);this.silver=x.silver,this.npcSales=x.npcSales,Cx(C),C&&this.questTick("sell"),C&&(this.log(`ขายสินค้า +${C} Silver`),this.ui())}),c6(E=>{if(this.deadUntil)return;if(e2(this,Date.now())||this.setAuto(!1),J){J.send(E);return}const x={...this,x:this.player.x,y:this.player.y},C=eM(x,E);C.ok&&(this.storage=x.storage,this.gear=x.gear,lt.play("pickup"),this.ui()),oy(C.text)},()=>J?.send({type:"storageOpen"})),HO(E=>{if(!this.deadUntil){if(J){J.send(E);return}Z5(this,E.gearId,E.card,E.replace===!0,E.index??0)&&(this.log("ฝังการ์ดสำเร็จ"),this.ui())}}),NO({onVector:E=>{E&&

etAuto(!this.autoPlay),skill:E=>this.useSkill(E),tapSkill:E=>this.useMobileSkill(E),holdSkill:E=>this.holdSkill(E),learn:E=>{this.deadUntil||(J?J.send({type:"learnSkills",levels:E}):K5(this,E)&&(this.questTick("learn"),this.ui()))},castLevel:(E,x)=>{this.deadUntil||(J?J.send({type:"skillCastLevel",skill:E,level:x}):S2(this,E,x)&&this.ui())}}),this.mountResetWindow(),i8(E=>{if(J){J.send(E);return}if(E.type==="repair"){const M={...this,x:this.player.x,y:this.player.y},P=q5(M);this.silver=M.silver??0,this.wearing=M.wearing,this.ui(),Hy(typeof P=="string"?P:`ซ่อมอุปกรณ์ ${P.count} ชิ้นแล้ว (−Silver ${P.cost.toLocaleString("en-US")})`);return}const x={...this,x:this.player.x,y:this.player.y},C=vM(x,E.gearI

);const y=this.time.delayedCall(uG,()=>{this.events.off("update",u),A.destroy(),this.skillCallouts.get(T)?.text===A&&this.skillCallouts.delete(T)});this.skillCallouts.set(T,{text:A,timer:y,follow:u})}questTick(c,S=1){(this.quest??=FC()).counters[c]=(this.quest.counters[c]??0)+S,this.refreshQuest()}claimQuest(){if(J){J.send({type:"claimQuest"});return}const c=kh(this.quest,this.level),S=DC(this);if(S){this.log(S);return}this.log(`รับรางวัล "${c?.quest.title}" สำเร็จ`),this.ui()}claimHunt(){if(J){J.send({type:"claimHunt"});return}const c=BC(this,Date.now());if(c){this.log(c);return}this.log(`รับรางวัลเควสล่ารายวันแล้ว — ${Cr({items:Nf})}`),lt.play("level");for(const[S,T]of Object.entries(Nf))Be(S,T);thi

at(c){if(this.deadUntil||this.stats[c]>=Xh)return;const S=Hh(this.stats[c]);if(!(this.points<S)){if(J){J.send({type:"stat",stat:c});return}this.points-=S,this.stats[c]++,c==="vit"&&(this.hp+=10),this.questTick("stat"),this.ui()}}spellBusyUntil=0;spellSerial=0;steerJoystick(c){const S=this.joystick;if(!S||this.deadUntil)return;this.sitting&&this.setSitting(!1);const T=["east","south-east","south","south-west","west","north-west","north","north-east"];if(this.art[0].direction=T[(Math.round(Math.atan2(S.y,S.x)/(Math.PI/4))+8)%8],this.faceLocalUntil=this.time.now+600,J){if(this.portalPending)return;const y=Date.now();if(y-this.joystickSentAt<120)return;this.joystickSentAt=y;const t=90,o=Math.round((this.p

.applyPotion(c)}applyPotion(c){const S=this.hp,T=rL(this.inventory,this.hp,this.maxHp,!this.deadUntil&&this.time.now>=this.potionReadyAt,c,ih(this).potionPct,Zt(this).total.vit);T&&(this.hp=T.hp,this.questTick("potion"),lt.play("potion"),this.potionReadyAt=this.time.now+lh,Qe(!0)&&wo(this,this.player),this.float(this.player.x,this.player.y-30,`+${this.hp-S} HP`,"#a8efaa"),this.log(`ใช้${mt[T.tier].name} +${this.hp-S} · เหลือยา HP รวม ${Tg(this.inventory)} ขวด`),this.ui())}teleport(c,S){this.setAuto(!1),this.cancelPickup(),this.target=null,this.destination=null,this.portalPending=null,this.paths.delete(this.player),this.player.setPosition(c,S),this.cameraAnchor.x=Math.floor(c),this.cameraAnchor.y=Math.

Full(),this.cancelPickup();return}S.splice(T,1),this.selectedDrop=null,this.pickupReadyAt=0,c.equipment?this.gear.push(c.equipment):c.item in this.inventory&&(this.inventory[c.item]+=c.count??1),this.questTick("pickup"),Be(c.item,c.count??1,c.equipment),lt.play("pickup"),this.lootViews.get(c)?.destroy(),this.lootViews.delete(c),this.log(`เก็บ ${c.equipment?Oe(c.equipment):mt[c.item].name} ×${c.count??1}`),this.refreshInventory(),this.autoScanAt=0}}}walkToward(c){if(c===this.area||this.deadUntil)return!1;const S=this.worldTravel.begin(this.area,c);return S?(this.setAuto(!1),this.cancelPickup(),this.headForPortal(S),!0):!1}headForPortal(c){this.portalPending=c,this.target=null,this.paths.delete(this.pla

his.notifyBagFull());return}const t=A(),o=t.indexOf(u);o>=0&&t.splice(o,1),this.selectedDrop===u&&this.cancelPickup(),this.lootViews.get(u)?.destroy(),this.lootViews.delete(u);const p=u.count??1;this.questTick("pickup"),Be(u.item,p,u.equipment),lt.play("pickup"),this.log(`กระต่ายเก็บ ${u.equipment?Oe(u.equipment):mt[u.item].name} ×${p}`+(y==="owner"?w.first==="owner"?" (เข้ากระเป๋าคุณ)":" (กระเป๋าสัตว์เลี้ยงเต็ม · เข้ากระเป๋าคุณ)":"")),this.refreshInventory(),this.autoScanAt=0}petLootFilter(){const c=this.autoLootMode.loot;return x0({consumption:c.consumption,etc:c.etc,card:c.card,equipment:c.equipment,lootOthers:this.autoLootMode.lootOthers===!0,skip:this.autoLootMode.lootSkip??[],weightCap:this.auto

ea,this.mobs.map(S=>({hp:S.hp,alive:S.alive,respawnAt:S.respawnAt,stomach:S.stomach}))),this.area=c.to,this.arrival=c.arrival,this.saveProgress(),this.worldTravel.next(this.area),c.to!=="field"&&this.questTick("travel"),this.scene.restart()}log(c){Br("system",c),this.logs.unshift(c),this.logs=this.logs.slice(0,50),St("log").replaceChildren(...this.logs.map(S=>{const T=document.createElement("p");return T.textContent=S,T}))}float(c,S,T,w="#ffffff"){const A=this.add.text(c,S,_(T),{fontSize:"17px",fontStyle:"bold",color:w,stroke:"#17202a",strokeThickness:3}).setOrigin(.5).setDepth(102e3);$e(A),this.tweens.add({targets:A,y:S-42,alpha:0,duration:850,onComplete:()=>A.destroy()})}move(c,S,T,w,A,u=0){if(et.Ma

his.mobs.indexOf(c)+1]?.setDead(!0),this.target=null,this.kills++,jC(this,Date.now())&&(this.log(`เควสล่ารายวันครบ ${n2} ตัวแล้ว — มารับ Refine Stone ที่หน้าต่าง Quest (กด Q)`),lt.play("level")),this.questTick("kill"),this.questTick("kill:"+c.name);const o=Math.round(c.reward*A6()*Cc(this.statuses,"expboost")),p=C5(this,j5(o));l1(c.name,this.level>=Ws?0:o,p),M5(this,p)&&this.float(this.player.x,this.player.y-50,`JOB LEVEL UP! ${this.jobLevel}`,"#ffe7aa"),this.collectLoot(c);for(let r=JC(this,o);r>0;r--){const i=this.level-r+1,s=z5(i);lt.play("level"),Qe(!0)&&Su(this,this.player),this.points+=s,this.hp=this.maxHp,this.sp=Zt(this).maxSp,this.float(this.player.x,this.player.y-35,`LEVEL UP! ${i}`,"#a8e6bd

.setDead(!0),this.target=null,this.kills++,jC(this,Date.now())&&(this.log(`เควสล่ารายวันครบ ${n2} ตัวแล้ว — มารับ Refine Stone ที่หน้าต่าง Quest (กด Q)`),lt.play("level")),this.questTick("kill"),this.questTick("kill:"+c.name);const o=Math.round(c.reward*A6()*Cc(this.statuses,"expboost")),p=C5(this,j5(o));l1(c.name,this.level>=Ws?0:o,p),M5(this,p)&&this.float(this.player.x,this.player.y-50,`JOB LEVEL UP! ${this.jobLevel}`,"#ffe7aa"),this.collectLoot(c);for(let r=JC(this,o);r>0;r--){const i=this.level-r+1,s=z5(i);lt.play("level"),Qe(!0)&&Su(this,this.player),this.points+=s,this.hp=this.maxHp,this.sp=Zt(this).maxSp,this.float(this.player.x,this.player.y-35,`LEVEL UP! ${i}`,"#a8e6bd"),this.log(`เลเวล ${i}

.send({type:"donate",amount:E})},E=>this.log(E)),yB(),NB(),DB(E=>this.log(E)),TP(),kP(),UR(()=>this.claimQuest(),()=>this.claimHunt(),E=>this.exchangeCoat(E)),ZR(()=>this.claimDaily()),document.getElementById("death-window")||document.getElementById("hud").insertAdjacentHTML("beforeend",'<section id="death-window" class="window death painted-pop" hidden role="alertdialog" aria-live="polite" aria-label="หมดสต

mount:E})},E=>this.log(E)),yB(),NB(),DB(E=>this.log(E)),TP(),kP(),UR(()=>this.claimQuest(),()=>this.claimHunt(),E=>this.exchangeCoat(E)),ZR(()=>this.claimDaily()),document.getElementById("death-window")||document.getElementById("hud").insertAdjacentHTML("beforeend",'<section id="death-window" class="window death painted-pop" hidden role="alertdialog" aria-live="polite" aria-label="หมดสติ"><div class="titleb

og(E)),TP(),kP(),UR(()=>this.claimQuest(),()=>this.claimHunt(),E=>this.exchangeCoat(E)),ZR(()=>this.claimDaily()),document.getElementById("death-window")||document.getElementById("hud").insertAdjacentHTML("beforeend",'<section id="death-window" class="window death painted-pop" hidden role="alertdialog" aria-live="polite" aria-label="หมดสติ"><div class="titlebar"><span>หมดสติ</span></div><div class="body deat

og(E)),yB(),NB(),DB(E=>this.log(E)),TP(),kP(),UR(()=>this.claimQuest(),()=>this.claimHunt(),E=>this.exchangeCoat(E)),ZR(()=>this.claimDaily()),document.getElementById("death-window")||document.getElementById("hud").insertAdjacentHTML("beforeend",'<section id="death-window" class="window death painted-pop" hidden role="alertdialog" aria-live="polite" aria-label="หมดสติ"><div class="titlebar"><span>หมดสติ</span>

